services:
  machineround:
    build: ./apps/machine-round
    ports:
      - "3001:3001"
    volumes:
      - ./apps/machine-round:/app
      - /app/node_modules
    working_dir: /app
    environment:
      - NODE_ENV=development
    command: npm run start

  browserround:
    build: ./apps/browser-round
    ports:
      - "3002:3002"
    volumes:
      - ./apps/browser-round:/app
      - /app/node_modules
    working_dir: /app
    command: npm run start

  server:
    build: ./apps/server
    ports:
      - "8080:5000"
    volumes:
      - ./apps/server:/app
      - /app/node_modules
    working_dir: /app
    command: npm run start
    develop:
      watch:
        - action: sync
          path: ./apps/server
          target: /app
  postgres:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@localhost.command
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres

volumes:
  pgdata:
