export const players = [
  {
    name: "Rohit Sharma",
    role: "Top-order batsman (c)",
    age: "38",
    Batting: 48.96, // ODI average
    Bowling: 0,
  },
  {
    name: "Shubman Gill",
    role: "Opening batsman (vc)",
    age: "25",
    Batting: 59.04, // ODI average :contentReference[oaicite:6]{index=6}
    Bowling: 0,
  },
  {
    name: "Virat Kohli",
    role: "Top-order batsman",
    age: "36",
    Batting: 57.88, // ODI average
    Bowling: 5,
  },
  {
    name: "Shreyas Iyer",
    role: "Middle-order batsman",
    age: "30",
    Batting: 37.71, // ODI average
    Bowling: 0,
  },
  {
    name: "KL Rahul",
    role: "Wicket‑keeper batsman",
    age: "33",
    Batting: 45.0,
    Bowling: 0,
  },
  {
    name: "Rishabh Pant",
    role: "Wicket‑keeper batsman",
    age: "27",
    Batting: 44.42,
    Bowling: 0,
  },
  {
    name: "Hardik Pandya",
    role: "All‑rounder",
    age: "31",
    Batting: 33.5,
    Bowling: 92,
  },
  {
    name: "Ravindra Jadeja",
    role: "All‑rounder",
    age: "36",
    Batting: 32.25,
    Bowling: 188,
  },
  {
    name: "Axar Patel",
    role: "All‑rounder",
    age: "30",
    Batting: 31.47,
    Bowling: 96,
  },
  {
    name: "Washington Sundar",
    role: "All‑rounder",
    age: "27",
    Batting: 26.75,
    Bowling: 25,
  },
  {
    name: "Abhishek Sharma",
    role: "All‑rounder",
    age: "24",
    Batting: 23.0,
    Bowling: 5,
  },
  {
    name: "Nitish Kumar Reddy",
    role: "All‑rounder",
    age: "24",
    Batting: 20.5,
    Bowling: 3,
  },
  {
    name: "Yashasvi Jaiswal",
    role: "Opening batsman",
    age: "23",
    Batting: 36.15, // T20I average (ODI debut too recent) :contentReference[oaicite:7]{index=7}
    Bowling: 0,
  },
  {
    name: "Sai Sudharsan",
    role: "Top-order batsman",
    age: "23",
    Batting: 34.0,
    Bowling: 0,
  },
  {
    name: "Rinku Singh",
    role: "Middle-order batsman",
    age: "28",
    Batting: 30.0,
    Bowling: 0,
  },
  {
    name: "Tilak Varma",
    role: "Middle-order batsman",
    age: "21",
    Batting: 31.2,
    Bowling: 0,
  },
  {
    name: "Dhruv Jurel",
    role: "Wicket‑keeper batsman",
    age: "23",
    Batting: 28.5,
    Bowling: 0,
  },
  {
    name: "Mohammed Shami",
    role: "Pace bowler",
    age: "34",
    Batting: 8.0,
    Bowling: 197,
  },
  {
    name: "Mohammed Siraj",
    role: "Pace bowler",
    age: "31",
    Batting: 7.85,
    Bowling: 140,
  },
  {
    name: "Arshdeep Singh",
    role: "Pace bowler",
    age: "27",
    Batting: 5.0,
    Bowling: 45,
  },
  {
    name: "Harshit Rana",
    role: "Pace bowler",
    age: "22",
    Batting: 10.0,
    Bowling: 8,
  },
  {
    name: "Prasidh Krishna",
    role: "Pace bowler",
    age: "29",
    Batting: 6.0,
    Bowling: 55,
  },
  {
    name: "Akash Deep",
    role: "Pace bowler",
    age: "28",
    Batting: 4.0,
    Bowling: 2,
  },
  {
    name: "Kuldeep Yadav",
    role: "Spin bowler",
    age: "33",
    Batting: 12.6,
    Bowling: 145,
  },
  {
    name: "Varun Chakravarthy",
    role: "Spin bowler",
    age: "29",
    Batting: 15.0,
    Bowling: 10,
  },
  {
    name: "Ravi Bishnoi",
    role: "Spin bowler",
    age: "23",
    Batting: 8.0,
    Bowling: 12,
  },
];
